<a href="https://colab.research.google.com/github/Shrey-Viradiya/PyTorch_for_DL/blob/master/Intro_to_Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Tue Sep 29 19:31:38 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8    10W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch

In [3]:
print(torch.cuda.is_available())
print(torch.rand(2,2))

True
tensor([[0.1259, 0.9672],
        [0.7492, 0.8124]])


In [4]:
x = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [5]:
x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [6]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [7]:
torch.ones(1,2) + torch.ones(1,2)

tensor([[2., 2.]])

In [8]:
torch.rand(1).item()

0.7448990345001221

In [9]:
cpu_tensor = torch.rand(2)
cpu_tensor.device

device(type='cpu')

In [10]:
gpu_tensor = cpu_tensor.to("cuda")
gpu_tensor.device

device(type='cuda', index=0)

In [11]:
torch.rand(2,2).max()

tensor(0.4483)

In [12]:
torch.rand(2,2).max().item()

0.5842242240905762

In [13]:
long_tensor = torch.tensor([[0,0,1],[0,0,0],[1,1,1]])
long_tensor.type()

'torch.LongTensor'

In [14]:
float_tensor = long_tensor.to(dtype = torch.float32)
float_tensor.type()

'torch.FloatTensor'

In [15]:
float_tensor

tensor([[0., 0., 1.],
        [0., 0., 0.],
        [1., 1., 1.]])

In [16]:
random_tensor = torch.rand(2,2)
random_tensor.log2()

tensor([[-0.0213, -3.3930],
        [-2.2912, -2.1003]])

In [17]:
random_tensor

tensor([[0.9853, 0.0952],
        [0.2043, 0.2332]])

In [18]:
random_tensor.log2_()

tensor([[-0.0213, -3.3930],
        [-2.2912, -2.1003]])

In [19]:
random_tensor

tensor([[-0.0213, -3.3930],
        [-2.2912, -2.1003]])

In [20]:
flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1,28,28)
viewed_tensor.shape

torch.Size([1, 28, 28])

In [21]:
reshaped_tensor = flat_tensor.reshape(1,28,28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

In [22]:
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2,0,1)
chw_tensor.shape

torch.Size([3, 640, 480])